rconsoleprint("@@WHITE@@")
rconsoleprint('- ')
wait(0.2)
rconsoleprint('c')
wait(0.2)
rconsoleprint('a')
wait(0.2)
rconsoleprint('r')
wait(0.2)
rconsoleprint('a')
wait(0.2)
rconsoleprint('c')
wait(0.2)
rconsoleprint('a')
wait(0.2)
rconsoleprint('l')
wait(0.2)
rconsoleprint('.')
wait(0.2)
rconsoleprint('l')
wait(0.2)
rconsoleprint('u')
wait(0.2)
rconsoleprint('a')
wait(0.2)
rconsoleprint(' ')
wait(0.2)
rconsoleprint('-')

